leftnav:
- identifier: 9a980034-8092-4f28-b266-9d315ebf6656
  name: About Terrascope
  pageRef: /external-resources/about-terrascope_9a980034-8092-4f28-b266-9d315ebf6656
  weight: 10
- identifier: 790fb91a-82c7-404c-85f3-f30ad1e9206f
  name: Solving Complex Problems
  pageRef: /external-resources/solving-complex-problems_790fb91a-82c7-404c-85f3-f30ad1e9206f
  weight: 20
- identifier: c46605fc-94b7-4344-8f1b-37fc534b26cc
  name: Design for Complex Environmental Issues
  pageRef: /external-resources/design-for-complex-environmental-issues_c46605fc-94b7-4344-8f1b-37fc534b26cc
  weight: 30
- identifier: 9c8a2707-dd2c-4e38-b10e-cc2a68577717
  name: Terrascope Radio
  pageRef: /external-resources/terrascope-radio_9c8a2707-dd2c-4e38-b10e-cc2a68577717
  weight: 40
- identifier: cf7ed524-ac32-4c02-b124-7048f438cd2b
  name: Past Years' Topics
  pageRef: /external-resources/past-years-topics_cf7ed524-ac32-4c02-b124-7048f438cd2b
  weight: 50
